//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uchet_Oborudovania.AppData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category_Oborudovania> Category_Oborudovania { get; set; }
        public virtual DbSet<Oborudovanie> Oborudovanie { get; set; }
        public virtual DbSet<Remonti> Remonti { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Sklad> Sklad { get; set; }
        public virtual DbSet<Spisanie> Spisanie { get; set; }
        public virtual DbSet<Status_Oborudovania> Status_Oborudovania { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Vidachi> Vidachi { get; set; }
    }
}
