//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uchet_Oborudovania.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oborudovanie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oborudovanie()
        {
            this.Remonti = new HashSet<Remonti>();
            this.Sklad = new HashSet<Sklad>();
            this.Spisanie = new HashSet<Spisanie>();
            this.Vidachi = new HashSet<Vidachi>();
        }
    
        public int ID_PC { get; set; }
        public int Seriyn_Num { get; set; }
        public int ID_Category { get; set; }
        public string Model { get; set; }
        public System.DateTime Date_Buy { get; set; }
        public string Garantia { get; set; }
        public int ID_Status { get; set; }
        public string Prichina_Spisania { get; set; }
        public Nullable<System.DateTime> Date_Spisania { get; set; }
        public Nullable<int> Sotrudnik_Spisal { get; set; }
    
        public virtual Category_Oborudovania Category_Oborudovania { get; set; }
        public virtual Status_Oborudovania Status_Oborudovania { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Remonti> Remonti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sklad> Sklad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spisanie> Spisanie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vidachi> Vidachi { get; set; }
    }
}
