//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uchet_Oborudovania.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remonti
    {
        public int ID_Remont { get; set; }
        public int ID_PC { get; set; }
        public string Company_Remont { get; set; }
        public string Prichina_Remonta { get; set; }
        public System.DateTime Date_Remonta { get; set; }
        public string Status_Remonta { get; set; }
        public int ID_Sotrudnika { get; set; }
        public System.DateTime Date_Sozdania { get; set; }
    
        public virtual Oborudovanie Oborudovanie { get; set; }
    }
}
