//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uchet_Oborudovania.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sklad
    {
        public int ID_Sklad { get; set; }
        public int ID_PC { get; set; }
        public System.DateTime Date_Postuplenia { get; set; }
        public Nullable<System.DateTime> Date_Vydachi { get; set; }
        public string Prichina { get; set; }
        public int Sotrudnik_Postavivshi { get; set; }
        public Nullable<int> Sotrudnik_Vydavshi { get; set; }
    
        public virtual Oborudovanie Oborudovanie { get; set; }
    }
}
