//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uchet_Oborudovania.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spisanie
    {
        public int ID_Spisanie { get; set; }
        public int ID_PC { get; set; }
        public System.DateTime Date_Spisania { get; set; }
        public string Prichina_Spisania { get; set; }
        public int Sotrudnik_Spisavshi { get; set; }
    
        public virtual Oborudovanie Oborudovanie { get; set; }
    }
}
