//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uchet_Oborudovania.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vidachi
    {
        public int ID_Vidachi { get; set; }
        public int ID_Sotrudnika { get; set; }
        public int ID_PC { get; set; }
        public System.DateTime Date_Vidachi { get; set; }
        public string Status_Vidachi { get; set; }
        public Nullable<System.DateTime> Date_Vozvrata { get; set; }
    
        public virtual Oborudovanie Oborudovanie { get; set; }
        public virtual Users Users { get; set; }
    }
}
